
-- Course Discussions Table
create table if not exists public.course_discussions (
  id bigint generated by default as identity primary key,
  allocation_id bigint references public.subject_allocations(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  content text,
  file_url text,
  file_name text,
  created_at timestamptz default now() not null
);

-- Real-time and RLS
alter table public.course_discussions enable row level security;

-- Faculty can see/send messages for their allocated subjects
create policy "Faculty can participate in assigned discussions"
  on course_discussions for all
  using (
    exists (
      select 1 from subject_allocations sa
      where sa.id = course_discussions.allocation_id and sa.faculty_id = auth.uid()
    )
  );

-- Students can see/send messages for their enrolled subjects
create policy "Students can participate in enrolled discussions"
  on course_discussions for all
  using (
    exists (
      select 1 from student_enrollments se
      where se.allocation_id = course_discussions.allocation_id and se.student_id = auth.uid()
    )
  );

-- Senders can delete their own messages
create policy "Users can delete own messages"
  on course_discussions for delete
  using ( sender_id = auth.uid() );

-- Enable Realtime
alter publication supabase_realtime add table course_discussions;
