
-- Meetings Table Schema
CREATE TABLE IF NOT EXISTS public.meetings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  agenda TEXT NOT NULL,
  location TEXT,
  organized_by TEXT,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'upcoming',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;

-- Faculty and HOD can see all meetings
CREATE POLICY "Everyone can see meetings"
  ON public.meetings FOR SELECT
  TO authenticated
  USING (true);

-- HOD and Admin can manage meetings
CREATE POLICY "HOD and Admin can manage meetings"
  ON public.meetings FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND (role = 'hod' OR role = 'admin')
    )
  );

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE meetings;
