
-- Create notes table
create table public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  title text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for notes
alter table public.notes enable row level security;

create policy "Users can view their own notes"
  on notes for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own notes"
  on notes for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own notes"
  on notes for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own notes"
  on notes for delete
  using ( auth.uid() = user_id );
