-- ============================================================
-- LMS Schema Extensions: modules, lessons, enrollments, progress, notes metadata, storage
-- Run after supabase_schema.sql and notes_schema.sql
-- ============================================================

-- Modules (belong to a course)
create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade not null,
  title text not null,
  "order" int default 0,
  created_at timestamptz default now() not null
);

alter table public.modules enable row level security;

create policy "Modules viewable by everyone"
  on modules for select using ( true );

create policy "Instructors can manage modules of own courses"
  on modules for all
  using (
    exists (
      select 1 from courses c
      where c.id = modules.course_id and c.instructor_id = auth.uid()
    )
  );

-- Lessons (belong to a module)
create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  module_id bigint references public.modules(id) on delete cascade not null,
  title text not null,
  content_url text,
  duration_minutes int,
  "order" int default 0,
  created_at timestamptz default now() not null
);

alter table public.lessons enable row level security;

create policy "Lessons viewable by everyone"
  on lessons for select using ( true );

create policy "Instructors can manage lessons"
  on lessons for all
  using (
    exists (
      select 1 from modules m
      join courses c on c.id = m.course_id
      where m.id = lessons.module_id and c.instructor_id = auth.uid()
    )
  );

-- Enrollments (student enrolled in course)
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  course_id bigint references public.courses(id) on delete cascade not null,
  enrolled_at timestamptz default now() not null,
  unique(user_id, course_id)
);

alter table public.enrollments enable row level security;

create policy "Users see own enrollments"
  on enrollments for select using ( auth.uid() = user_id );

create policy "Users can enroll themselves"
  on enrollments for insert with check ( auth.uid() = user_id );

create policy "Instructors see enrollments for their courses"
  on enrollments for select
  using (
    exists (
      select 1 from courses c
      where c.id = enrollments.course_id and c.instructor_id = auth.uid()
    )
  );

-- Lesson progress (completion tracking)
create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  lesson_id bigint references public.lessons(id) on delete cascade not null,
  completed_at timestamptz default now() not null,
  unique(user_id, lesson_id)
);

alter table public.lesson_progress enable row level security;

create policy "Users see own progress"
  on lesson_progress for select using ( auth.uid() = user_id );

create policy "Users can insert own progress"
  on lesson_progress for insert with check ( auth.uid() = user_id );

create policy "Instructors see progress for their course lessons"
  on lesson_progress for select
  using (
    exists (
      select 1 from lessons l
      join modules m on m.id = l.module_id
      join courses c on c.id = m.course_id
      where l.id = lesson_progress.lesson_id and c.instructor_id = auth.uid()
    )
  );

-- Extend notes: optional course_id and module_id for linking
alter table public.notes
  add column if not exists course_id bigint references public.courses(id) on delete set null,
  add column if not exists module_id bigint references public.modules(id) on delete set null,
  add column if not exists updated_at timestamptz default now();

create policy "Users can update own notes"
  on notes for update using ( auth.uid() = user_id );

-- Notes metadata for Supabase Storage (file path, type)
create table if not exists public.notes_files (
  id bigint generated by default as identity primary key,
  note_id bigint references public.notes(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade not null,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  created_at timestamptz default now() not null
);

alter table public.notes_files enable row level security;

create policy "Users see own note files"
  on notes_files for select using ( auth.uid() = user_id );

create policy "Users insert own note files"
  on notes_files for insert with check ( auth.uid() = user_id );

create policy "Users delete own note files"
  on notes_files for delete using ( auth.uid() = user_id );

-- Instructors can update/delete their own courses (run after supabase_schema.sql)
create policy "Instructors can update own courses"
  on courses for update using ( instructor_id = auth.uid() );

create policy "Instructors can delete own courses"
  on courses for delete using ( instructor_id = auth.uid() );

-- Course resources (PDFs, files uploaded by instructor for a course)
create table if not exists public.course_resources (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade not null,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz default now() not null
);

alter table public.course_resources enable row level security;

create policy "Course resources viewable by everyone"
  on course_resources for select using ( true );

create policy "Instructors can insert resources for own courses"
  on course_resources for insert
  with check (
    uploaded_by = auth.uid()
    AND
    exists (select 1 from courses c where c.id = course_resources.course_id and c.instructor_id = auth.uid())
  );

create policy "Instructors can delete resources for own courses"
  on course_resources for delete
  using (
    exists (select 1 from courses c where c.id = course_resources.course_id and c.instructor_id = auth.uid())
  );

-- Storage: create buckets in Supabase Dashboard > Storage
-- 1. student-notes: for student notes and PDFs (private, RLS: user can read/write own path)
-- 2. course-resources: for instructor uploads (RLS: instructor can write to own course folder)
